const { exec, execFile } = require("child_process");
const _ = require("lodash");
// const data = {
//   id: newId,
//   message:
//     "aplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqo"
// };

//write a function that executes an exec function
let newId = 12345;
const number = _.range(20);
const outputHandler = (error, stdout, stderr) => {
  console.error(error)
  console.log(stderr)
}

exec(`nodemon`, outputHandler)

number.map(el => {
  exec(`node src/controllers/clientController.js ${el + newId}`, outputHandler);
});


setTimeout(()=> {
  number.map(el => {
    exec(`pkill -U ${el}`, outputHandler)
  })
    exec(`killall nodemon`)
}, 1000 * 60 * 60)

// process.stdin.resume();