const io = require("socket.io-client");
const args = process.argv.slice(2);
const _ = require("lodash");
const fs = require('fs');

 
    
    const data = {
      id: Number(args[0]),
      message: 
          "aplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqoaplwekgiapasleinvpsdlkjasd;flkja;dlfkja;sldkfj;alskdj;lkjianeiofiojhasefiojefaepooipiepwipewriouperwiouperwoipueriuopewriouperwioueiopurewqo"
    };
    const interval = () => {
      socket.emit("join new room", data);
      fs.appendFile(`test2/${data.id}`, data.id + "\n", (err) => {
        if (err) throw err
        console.log('File Append Successful')
    })
    };
    var socket = io.connect("http://localhost:3550");
    setInterval(interval, _.random(2000, 6000));
    setInterval(interval, _.random(2000, 6000));
    setInterval(interval, _.random(2000, 6000));
    setInterval(interval, _.random(2000, 6000));
    
    process.stdin.resume();
  
